// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package in.dealo.entity;

import in.dealo.entity.PaymentGateway;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect PaymentGateway_Roo_Configurable {
    
    declare @type: PaymentGateway: @Configurable;
    
}
