// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package in.dealo.entity;

import in.dealo.entity.Subscriber;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Subscriber_Roo_Configurable {
    
    declare @type: Subscriber: @Configurable;
    
}
